### PR TITLE
Fixes PLAP-Option

### PR DESCRIPTION
**Pull request by anicoa**

### CODE REVIEW

**Comment by egon0** [comment]
Looks good to me, please merge soon, it's a hassle currently to manually fix this problem l on every client 😐

**Comment by Lun4r161** [comment]
The merge is not "live" i think. Chocy downloaded the old chocolateyInstall.ps1.
https://github.com/dgalbraith/chocolatey-packages/issues/524#issue-2112626787

**Comment by anicoa** [comment]
@dgalbraith any chance to get the new version released or do we have to wait for the next OpenVPN release? I can help if it helps ;)

**Comment by dgalbraith** [comment]
@anicoa should be available with the package in the community repository now - ```2.6.9.001```.

**Pull request merged**
