### PR TITLE
(gh-353) Update Winaero Tweaker version to 1.30

### PR DESCRIPTION
**Pull request by wilsenhc**
Updated the versions and checksums for the Winaero Tweaker package. Base, install and portable versions

Referencing #353

### CODE REVIEW

**Review by dgalbraith — CHANGES_REQUESTED** [review]
Would it be possible to update the version to 1.30.0.0 - the additional digit is significant as the embedded archive in the download uses 4 digits and the install will not function correctly without this matching.

Could the release notes in the .nuspec files also be updated to reflect the 1.30 version?  The URL for this is [https://winaero.com/winaero-tweaker-1-30-is-here-allows-you-to-move-windows-11-taskbar-and-more](https://winaero.com/winaero-tweaker-1-30-is-here-allows-you-to-move-windows-11-taskbar-and-more)

**Comment by wilsenhc** [comment]
Yes indeed, I'll make the changes and update.

Didn't knwo the version number would generate problems with the history

**Comment by wilsenhc** [comment]
Made the requested changes now

**Comment by wilsenhc** [comment]
Want to know something NOT cool? Winaero Tweaker has already released a 1.31.0.0 version

**Comment by dgalbraith** [comment]
Thanks for the contribution!

Noticed that there was some crossover there - another update pushed for 1.31.0.0.

**Pull request merged**
